### ISSUE TITLE
Error: no module named 'mappy'

### ISSUE THREAD

**Issue by jagos01** [poeli/PanGIA#1]
Hello,
I get the following error while running PanGIA.

Traceback (most recent call last):
  File "./pangia.py", line 2278, in <module>
    genome_size, host_genome = getStrainSize( argvs.database )
  File "./pangia.py", line 2055, in getStrainSize
    import mappy
ModuleNotFoundError: No module named 'mappy'

The command used was as follows:
pangia.py -i /home/Desktop/guppy_basecalled/basecall_combined.fastq -d /home/data0/pangia_db/PanGIA/NCBI_genomes_refseq89_*.fa.mmi -t 70 --keepTemp -rm minimap2

Does pangia currently work with minimap2 or only bwa?  Are bwa index files available or do they have to be generated from the 20180915_NCBI_genomes_refseq89*.fa.tar files?  I have attached the log file if need.
[basecall_combined.pangia.log](https://github.com/poeli/PanGIA/files/5087209/basecall_combined.pangia.log)

Thanks,
Scott

**Comment by jagos01** [comment]
So I installed the mappy module, pangia now returns the following error:
Traceback (most recent call last):
  File "/home/DRDC/pangia/pangia.py", line 2320, in <module>
    res_rollup = taxonomyRollUp(res, patho_meta, mapped_r_cnt, argvs.minRsnb, argvs.minReads, argvs.minLen, argvs.minCov, argvs.minDc)
  File "/home/pangia/pangia.py", line 1199, in taxonomyRollUp
    genome_size[taxid]
KeyError: '546272'

I also noticed lines 2052 & 2053 in pangia.py are
WARNING: This is not working!!!
The mappy library seems to have issue not reporting all seq_names.
Should bwa be used instead of minimap2?
Thanks,
Scott

**Comment by poeli-lanl** [comment]
Hey Scott,

I don't think I use mappy anymore (as comment). Will get back to you shortly.

Thanks,
Paul

**Comment by jagos01** [comment]
Hello Paul,
Depending on the dataset used, the  error reported earlier generates a
KeyError for different taxid.
Thanks for your help.
Scott

**Comment by jagos01** [comment]
I could not get this to work with the .mmi files alone.  I needed to include the bwa index files for PanGIA to work. 
Thanks,
Scott
